import { createFileRoute } from '@tanstack/react-router';

export const Route = createFileRoute('/privacy')({
  component: PrivacyPolicy,
});

function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="container-edit py-16 md:py-24 max-w-4xl">
        <h1 className="font-serif text-5xl md:text-7xl font-bold uppercase mb-8 border-b-4 border-black pb-4">Privacy Policy</h1>
        
        <div className="space-y-8 font-serif text-lg leading-relaxed">
          <section>
            <h2 className="text-2xl font-bold uppercase mb-4">Introduction</h2>
            <p>Welcome to Capital Chronicle. We respect your privacy and are committed to protecting your personal data. This privacy policy will inform you as to how we look after your personal data when you visit our website and tell you about your privacy rights and how the law protects you.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold uppercase mb-4">Definitions</h2>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>Personal Data</strong> means any information relating to an identified or identifiable natural person.</li>
              <li><strong>Service</strong> means the Capital Chronicle website and its associated features.</li>
              <li><strong>Usage Data</strong> is data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold uppercase mb-4">Information We Collect</h2>
            <p>We may collect, use, store and transfer different kinds of personal data about you which we have grouped together as follows:</p>
            <ul className="list-disc pl-6 mt-4 space-y-2">
              <li><strong>Identity Data</strong> includes first name, last name, username or similar identifier.</li>
              <li><strong>Contact Data</strong> includes email address and telephone numbers.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold uppercase mb-4">Information You Voluntarily Provide</h2>
            <p>When you fill out forms on our site (such as our Enquiry forms), you voluntarily provide us with Personal Data including your Name, Email, Contact Number, and any Message content. This information is submitted explicitly by you for the purpose of communicating with our team.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold uppercase mb-4">Automatically Collected Information</h2>
            <p>As you interact with our website, we may automatically collect Technical Data about your equipment, browsing actions, and patterns. We collect this personal data by using cookies, server logs, and other similar technologies.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold uppercase mb-4">Purpose of Data Collection</h2>
            <p>We use your data to:</p>
            <ul className="list-disc pl-6 mt-4 space-y-2">
              <li>Provide, operate, and maintain our website.</li>
              <li>Improve, personalize, and expand our website.</li>
              <li>Understand and analyze how you use our website.</li>
              <li>Communicate with you, either directly or through one of our partners, including for customer service and to provide you with updates and other information relating to the website.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold uppercase mb-4">Legal Basis for Processing</h2>
            <p>Where applicable under the GDPR, our legal basis for collecting and using the personal information described above will depend on the personal information concerned and the specific context in which we collect it. We normally collect personal information from you only where we have your consent to do so or where the processing is in our legitimate interests.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold uppercase mb-4">How We Use Personal Information</h2>
            <p>We use the information we collect in various ways, including to respond to your inquiries submitted via our contact forms, send you emails, and find and prevent fraud.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold uppercase mb-4">CRM and Third-Party Service Providers</h2>
            <p>Information submitted through our Contact and Enquiry forms is securely transmitted to and stored within our third-party Customer Relationship Management (CRM) system provided by CRM Core (inwo.crmcore.me) to process and manage your requests. Our Login forms do not send data to this CRM. We do not expose API tokens or sensitive backend credentials in our frontend code.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold uppercase mb-4">Cookies and Tracking Technologies</h2>
            <p>We use cookies and similar tracking technologies to track the activity on our Service and hold certain information. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold uppercase mb-4">Data Security Measures</h2>
            <p>We have put in place appropriate security measures to prevent your personal data from being accidentally lost, used, or accessed in an unauthorized way, altered, or disclosed. All CRM requests are performed securely through server-side API routes using encrypted environment variables.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold uppercase mb-4">Data Retention</h2>
            <p>We will only retain your personal data for as long as necessary to fulfill the purposes we collected it for, including for the purposes of satisfying any legal, accounting, or reporting requirements.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold uppercase mb-4">International Data Transfers</h2>
            <p>Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country, or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold uppercase mb-4">User Rights</h2>
            <p>Under certain circumstances, you have rights under data protection laws in relation to your personal data. These include the right to request access, correction, erasure, restriction, transfer, to object to processing, to portability of data and (where the lawful ground of processing is consent) to withdraw consent.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold uppercase mb-4">Marketing Communications</h2>
            <p>You will receive marketing communications from us if you have requested information from us or purchased goods or services from us and you have not opted out of receiving that marketing.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold uppercase mb-4">Children's Privacy</h2>
            <p>Our Service does not address anyone under the age of 18. We do not knowingly collect personally identifiable information from anyone under the age of 18.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold uppercase mb-4">Third-Party Websites</h2>
            <p>Our Service may contain links to other websites that are not operated by us. If you click on a third-party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold uppercase mb-4">Policy Updates</h2>
            <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold uppercase mb-4">Contact Information</h2>
            <p>If you have any questions about this Privacy Policy, please contact us via our Enquiry page.</p>
          </section>

          <section>
            <p className="text-sm italic">Last Updated Date: June 18, 2026</p>
          </section>
        </div>
      </div>
      
      {/* Footer */}
      <footer className="border-t-4 border-black py-6 text-center font-sans font-bold uppercase text-xs mt-16">
        <p>© {new Date().getFullYear()} Capital Chronicle. Printed in the Digital Era.</p>
        <div className="mt-4 flex justify-center space-x-4">
          <a href="/privacy" className="hover:underline">Privacy Policy</a>
          <a href="/terms" className="hover:underline">Terms & Conditions</a>
        </div>
      </footer>
    </div>
  );
}
